=pod

=head1 NAME

 - protoview -
Make statistiques with protocols wich come to your interface

=head1 SYNOPSIS

protoview [OPTIONS]


=head1 OPTIONS

=over 4

=item B<-i -iface>

Specify the interface to sniff

=item B<-r -refresh>

Refresh time in seconds (default: 1 second)

=item B<-n -nocolor>

Don't color the terminal

=item B<-v -version>

Print version

=item B<-h -help>

Print help

=item B<-m -man>

Print complete help

=back

=head1 CONTROLS

=over 4

=item B<PAGE UP>

Scroll backward

=item B<PAGE DOWN>

Scroll forward

=item B<ARROWS>

Browse into the window

=back

=head1 DESCRIPTION

B<This program> is a network monitoring tool using Curses.
It make statistiques with protocols wich are used on your network.

=head1 SCREENSHOTS

L<https://github.com/t00sh/protoview/blob/master/screenshots/version-1-0.jpg>

=begin html

<p>
   <img src="https://github.com/t00sh/protoview/blob/master/screenshots/version-1-0.jpg" alt="screen" />
</p>

=end html

=head1 DEPENDS

=over 4

=item B<perl 5>

=item B<Net::Pcap>

=item B<Curses>

=back

=head1 PROTOCOLS

=over 4

=item B<L2>

=over 4

=item Ethernet

=back

=back

=over 4

=item B<L3>

=over 4

=item IPv4

=item IPv6

=back

=back

=head1 LICENCE

This program is a free software. 
It is distrubued with the terms of the B<GPLv3 licence>.

=head1 VERSION

V1.0-beta

=head1 AUTHOR

Written by B<Tosh>

(duretsimon73 -at- gmail -dot- com)

